In [ ]:
################ iterating the ndarray ###################
#By using for loop
#By using while loop
########### 1D - ARRAY  #############
import numpy as np
lst=[i for i in range(1,10)]
arr=np.array(lst)
print(arr,type(arr))

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [ ]:
################ USING FOR LOOP ##################
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9


In [4]:
############### USING WHILE LOOP ##################
i=0
while i<len(arr):
    print(arr[i])
    i+=1

1
2
3
4
5
6
7
8
9


In [ ]:
########### 2D - ARRAY ############
arr=np.array([i for i in range(1,10)]).reshape((3,3))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
########## USING FOR LOOP ############
### getting only rows
for i in range(len(arr)):
    print(arr[i])

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
########## USING WHILE LOOP ############
### getting only rows
i=0
while i<len(arr):
    print(arr[i])
    i+=1

[1 2 3]
[4 5 6]
[7 8 9]


In [9]:
############## getting the elements from ndarray by using element by element ###################
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
############# by using for loop ###############
for i in range(len(arr)):
    for j in range(len(arr[i])):
        print(arr[i][j])

1
2
3
4
5
6
7
8
9


In [14]:
############# by using while loop ###############
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
i=0
while i<len(arr):
    j=0
    while j<len(arr[i]):
        print(arr[i][j])
        j+=1
    i+=1

1
2
3
4
5
6
7
8
9


In [ ]:
########### 3D - ARRAY   ##########
arr=np.array([i for i in range(1,19)]).reshape((2,3,3))
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [ ]:
###### getting each matrix - using for loop ########
for i in arr:
    print(i)
    print()

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[10 11 12]
 [13 14 15]
 [16 17 18]]



In [ ]:
###### getting each matrix - using while loop ######
i=0
while i<len(arr):
    print(arr[i])
    print()
    i+=1

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[10 11 12]
 [13 14 15]
 [16 17 18]]



In [23]:
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [ ]:
############# getting each row from each matrix - using for loop ############
for i in range(len(arr)):
    for j in range(len(arr[i])):
        print(arr[i][j])
        print()
    print('-----------------------')

[1 2 3]

[4 5 6]

[7 8 9]

-----------------------
[10 11 12]

[13 14 15]

[16 17 18]

-----------------------


In [28]:
############# getting each row from each matrix - using while loop #############
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [31]:
i=0
while i<len(arr):
    j=0
    while j<len(arr[i]):
        print(arr[i][j])
        print()
        j+=1
    print('----------------')
    i+=1

[1 2 3]

[4 5 6]

[7 8 9]

----------------
[10 11 12]

[13 14 15]

[16 17 18]

----------------


In [32]:
############# fetching elements one by one - using for loop ################
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [39]:
for i in range(len(arr)):
    for j in range(len(arr[i])):
        for k in range(len(arr[i][j])):
            print(f'Element at arr[{i}][{j}][{k}] index is {arr[i][j][k]}')


Element at arr[0][0][0] index is 1
Element at arr[0][0][1] index is 2
Element at arr[0][0][2] index is 3
Element at arr[0][1][0] index is 4
Element at arr[0][1][1] index is 5
Element at arr[0][1][2] index is 6
Element at arr[0][2][0] index is 7
Element at arr[0][2][1] index is 8
Element at arr[0][2][2] index is 9
Element at arr[1][0][0] index is 10
Element at arr[1][0][1] index is 11
Element at arr[1][0][2] index is 12
Element at arr[1][1][0] index is 13
Element at arr[1][1][1] index is 14
Element at arr[1][1][2] index is 15
Element at arr[1][2][0] index is 16
Element at arr[1][2][1] index is 17
Element at arr[1][2][2] index is 18


In [40]:
############# fetching elements one by one - using while loop ################
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [42]:
i=0
while i<len(arr):
    j=0
    while j<len(arr[i]):
        k=0
        while k<len(arr[i][j]):
            print(f'Element at arr[{i}][{j}][{k}] is {arr[i][j][k]}')
            k+=1
        j+=1
    i+=1

Element at arr[0][0][0] is 1
Element at arr[0][0][1] is 2
Element at arr[0][0][2] is 3
Element at arr[0][1][0] is 4
Element at arr[0][1][1] is 5
Element at arr[0][1][2] is 6
Element at arr[0][2][0] is 7
Element at arr[0][2][1] is 8
Element at arr[0][2][2] is 9
Element at arr[1][0][0] is 10
Element at arr[1][0][1] is 11
Element at arr[1][0][2] is 12
Element at arr[1][1][0] is 13
Element at arr[1][1][1] is 14
Element at arr[1][1][2] is 15
Element at arr[1][2][0] is 16
Element at arr[1][2][1] is 17
Element at arr[1][2][2] is 18


In [ ]:
####################################### X #######################################