In [ ]:
############## Advanced looping on ndarray objects ##################
#######Iterating Arrays Using nditer()
#1D array
import numpy as np
arr=np.array([i for i in range(100,109)])
for i in np.nditer(arr):
    print(i)


100
101
102
103
104
105
106
107
108


In [5]:
#2D array
import numpy as np
arr=np.array([i for i in range(100,109)]).reshape((3,3))
print(arr)
print('----------------')
for i in np.nditer(arr):
    print(i)

[[100 101 102]
 [103 104 105]
 [106 107 108]]
----------------
100
101
102
103
104
105
106
107
108


In [6]:
#3D array
import numpy as np
arr=np.array([i for i in range(3*3*3)]).reshape((3,3,3))
print(arr)
print('----------------')
for i in np.nditer(arr):
    print(i)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
----------------
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [ ]:
for i in np.nditer(arr,order='C'): #C means row major which is default
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [ ]:
for i in np.nditer(arr,order='F'): #F means column major
    print(i)

0
9
18
3
12
21
6
15
24
1
10
19
4
13
22
7
16
25
2
11
20
5
14
23
8
17
26


In [ ]:
############# enumerated iteration using numpy.ndenumerate() ############
#it gives index along with element
#i.e. position and value inside a tuple
#1D array
import numpy as np
arr=np.array([i for i in range(100,109)])
for i in np.ndenumerate(arr):
    print(i,type(i))


((0,), np.int64(100)) <class 'tuple'>
((1,), np.int64(101)) <class 'tuple'>
((2,), np.int64(102)) <class 'tuple'>
((3,), np.int64(103)) <class 'tuple'>
((4,), np.int64(104)) <class 'tuple'>
((5,), np.int64(105)) <class 'tuple'>
((6,), np.int64(106)) <class 'tuple'>
((7,), np.int64(107)) <class 'tuple'>
((8,), np.int64(108)) <class 'tuple'>


In [13]:
for i in np.ndenumerate(arr):
    print(f'The element at {i[0][0]} index is {i[1]}')

The element at 0 index is 100
The element at 1 index is 101
The element at 2 index is 102
The element at 3 index is 103
The element at 4 index is 104
The element at 5 index is 105
The element at 6 index is 106
The element at 7 index is 107
The element at 8 index is 108


In [14]:
#2D array
import numpy as np
arr=np.array([i for i in range(100,109)]).reshape(3,3)
for i in np.ndenumerate(arr):
    print(i,type(i))


((0, 0), np.int64(100)) <class 'tuple'>
((0, 1), np.int64(101)) <class 'tuple'>
((0, 2), np.int64(102)) <class 'tuple'>
((1, 0), np.int64(103)) <class 'tuple'>
((1, 1), np.int64(104)) <class 'tuple'>
((1, 2), np.int64(105)) <class 'tuple'>
((2, 0), np.int64(106)) <class 'tuple'>
((2, 1), np.int64(107)) <class 'tuple'>
((2, 2), np.int64(108)) <class 'tuple'>


In [15]:
for i in np.ndenumerate(arr):
    print(f'The element at row = {i[0][0]}, column = {i[0][1]} is {i[1]}')

The element at row = 0, column = 0 is 100
The element at row = 0, column = 1 is 101
The element at row = 0, column = 2 is 102
The element at row = 1, column = 0 is 103
The element at row = 1, column = 1 is 104
The element at row = 1, column = 2 is 105
The element at row = 2, column = 0 is 106
The element at row = 2, column = 1 is 107
The element at row = 2, column = 2 is 108


In [16]:
#3D array
import numpy as np
arr=np.array([i for i in range(3*3*3)]).reshape((3,3,3))
print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [17]:
for i in np.ndenumerate(arr):
    print(i,type(i))

((0, 0, 0), np.int64(0)) <class 'tuple'>
((0, 0, 1), np.int64(1)) <class 'tuple'>
((0, 0, 2), np.int64(2)) <class 'tuple'>
((0, 1, 0), np.int64(3)) <class 'tuple'>
((0, 1, 1), np.int64(4)) <class 'tuple'>
((0, 1, 2), np.int64(5)) <class 'tuple'>
((0, 2, 0), np.int64(6)) <class 'tuple'>
((0, 2, 1), np.int64(7)) <class 'tuple'>
((0, 2, 2), np.int64(8)) <class 'tuple'>
((1, 0, 0), np.int64(9)) <class 'tuple'>
((1, 0, 1), np.int64(10)) <class 'tuple'>
((1, 0, 2), np.int64(11)) <class 'tuple'>
((1, 1, 0), np.int64(12)) <class 'tuple'>
((1, 1, 1), np.int64(13)) <class 'tuple'>
((1, 1, 2), np.int64(14)) <class 'tuple'>
((1, 2, 0), np.int64(15)) <class 'tuple'>
((1, 2, 1), np.int64(16)) <class 'tuple'>
((1, 2, 2), np.int64(17)) <class 'tuple'>
((2, 0, 0), np.int64(18)) <class 'tuple'>
((2, 0, 1), np.int64(19)) <class 'tuple'>
((2, 0, 2), np.int64(20)) <class 'tuple'>
((2, 1, 0), np.int64(21)) <class 'tuple'>
((2, 1, 1), np.int64(22)) <class 'tuple'>
((2, 1, 2), np.int64(23)) <class 'tuple'>
((

In [18]:
for i in np.ndenumerate(arr):
    print(f'The element at matrix = {i[0][0]}, row = {i[0][1]}, column ={i[0][2]} is {i[1]}')

The element at matrix = 0, row = 0, column =0 is 0
The element at matrix = 0, row = 0, column =1 is 1
The element at matrix = 0, row = 0, column =2 is 2
The element at matrix = 0, row = 1, column =0 is 3
The element at matrix = 0, row = 1, column =1 is 4
The element at matrix = 0, row = 1, column =2 is 5
The element at matrix = 0, row = 2, column =0 is 6
The element at matrix = 0, row = 2, column =1 is 7
The element at matrix = 0, row = 2, column =2 is 8
The element at matrix = 1, row = 0, column =0 is 9
The element at matrix = 1, row = 0, column =1 is 10
The element at matrix = 1, row = 0, column =2 is 11
The element at matrix = 1, row = 1, column =0 is 12
The element at matrix = 1, row = 1, column =1 is 13
The element at matrix = 1, row = 1, column =2 is 14
The element at matrix = 1, row = 2, column =0 is 15
The element at matrix = 1, row = 2, column =1 is 16
The element at matrix = 1, row = 2, column =2 is 17
The element at matrix = 2, row = 0, column =0 is 18
The element at matrix 